version: "3.1"

services:
  oidc-django:
    build: .
    environment:
      OIDC_DB_USER: ${POSTGRESQL_USER}
      OIDC_DB_PASSWORD: ${POSTGRESQL_PASSWORD}
      OIDC_DB_NAME: ${POSTGRESQL_DATABASE}
      OIDC_DB_PORT: 5432
      ACAPY_ADMIN_PORT: ${AGENT_ADMIN_PORT}
      ACAPY_TRANSPORT_PORT: ${AGENT_HTTP_PORT}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      SECRET_KEY: ${SECRET_KEY}
      SITE_URL: ${SITE_URL}
      DEBUG: ${DEBUG}
    networks:
       - oidc
    ports:
      - 5000:8080
    depends_on:
      - oidc-db
      - aca-py
      
  oidc-db:
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest
    environment:
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
    ports:
      - ${EXPOSED_DATABASE_SERVICE_PORT}:5432
    volumes:
      - db-volume:/var/lib/pgsql/data
    networks:
      - oidc
      
      
  aca-py:
    image: bcgovimages/aries-cloudagent:py36-1.15-1_0.6.0
    ports:
      - ${AGENT_ADMIN_PORT}:${AGENT_ADMIN_PORT}
      - ${AGENT_HTTP_PORT}:${AGENT_HTTP_PORT}
    networks:
      - oidc
    entrypoint: /bin/bash
    command: [
      "-c",
      "aca-py start \
        --inbound-transport http '0.0.0.0' ${AGENT_HTTP_PORT} \
        --outbound-transport http \
        --endpoint ${AGENT_ENDPOINT} \
        --genesis-url '${GENESIS_URL}' \
        --auto-verify-presentation \
        --wallet-type 'indy' \
        --wallet-name 'oidc_agent_wallet1' \
        --wallet-key '${WALLET_ENCRYPTION_KEY}' \
        --seed '${AGENT_SEED}' \
        --admin '0.0.0.0' ${AGENT_ADMIN_PORT} \
        --${ACAPY_ADMIN_MODE} \
        --label ${AGENT_NAME} \
        --webhook-url ${IDENTITY_SERVER_WEB_HOOK_URL} \
        --auto-provision",
        ]

volumes:
  db-volume:

networks:
  oidc:
