# Generated by Django 3.1 on 2020-08-12 13:56

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('presentation_record_id', models.CharField(max_length=255)),
                ('presentation_request_id', models.CharField(max_length=255)),
                ('presentation_request', models.JSONField()),
                ('presentation_request_satisfied', models.BooleanField(default=False)),
                ('expired_timestamp', models.DateTimeField(blank=True, null=True)),
                ('request_parameters', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MappedUrl',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PresentationConfigurations',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('verified_email', models.CharField(max_length=255)),
                ('configuration', models.JSONField()),
            ],
        ),
    ]
