# Generated by Django 3.1 on 2020-08-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oidc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentationconfigurations',
            old_name='verified_email',
            new_name='subject_identifier',
        ),
    ]
