# Generated by Django 3.1 on 2020-08-17 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("oidc", "0002_auto_20200813_0817")]

    operations = [
        migrations.RemoveField(model_name="authsession", name="id"),
        migrations.AddField(
            model_name="authsession",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
