# Generated by Django 3.1 on 2020-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc', '0003_auto_20200817_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='authsession',
            name='presentation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
