# Generated by Django 3.1 on 2020-08-24 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc', '0004_authsession_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappedurl',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oidc.authsession'),
        ),
    ]
